[package]
name = "just_traits"
version = "0.1.0"
authors = ["Adam Winiarczuk <adamosca@gmail.com>"]
edition = "2018"

[build-dependencies]

[dependencies]
legion = "=0.2.1"
nalgebra-glm = {version="0.4.0", features=["serde-serialize"]}
